name: Deploy to IONOS

on:
  push:
    branches:
      - main  # Change this to the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to IONOS via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./
        server-dir: /path/to/your/site  # Replace with the path where you want to deploy your site
        protocol: ftps  # Use 'sftp' for SFTP
